"""empty message

Revision ID: 578a64844ec0
Revises: 
Create Date: 2020-06-30 19:57:46.620303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578a64844ec0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('image_link', sa.String(length=500), nullable=True))
    op.alter_column('artist', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'artist', 'venue', ['venue_id'], ['id'])
    op.drop_column('artist', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'artist', type_='foreignkey')
    op.alter_column('artist', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('artist', 'image_link')
    # ### end Alembic commands ###
